### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by raspgalax** [EngineerYo/Exapunks-Automation#4]
Great work on this! Which program are you using to run it in the second gif? I installed Pillow and pyautogui. In an admin Powershell it runs for a second and then spits out:

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\Github\Exapunks-Automation\main.py", line 207, in <module>
    main()
  File "C:\Users\User\Documents\Github\Exapunks-Automation\main.py", line 205, in main
    board.play_games(10)
  File "C:\Users\User\Documents\Github\Exapunks-Automation\main.py", line 161, in play_games
    game = self.make_game()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\Github\Exapunks-Automation\main.py", line 91, in make_game
    rank_stacks = Stack.from_cards(rank_cards[cards_idx])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\Github\Exapunks-Automation\Stack.py", line 51, in from_cards
    stacks.append(Stack(card, card, 1))
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\Github\Exapunks-Automation\Stack.py", line 79, in __init__
    self.is_faces = self.back.value == 'F'
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by Will-Crain** [comment]
Hey there! It's been a while since I've looked at this code, but I will take a look this afternoon & evening

I would normally execute main.py via command line (windows command prompt or in Visual Studio Code's integrated command line)

One thing you should make sure of is that the screen with Exapunks up is unobstructed and is on your primary display. I had to get creative with where I put the command line so that the computer could see the full game space. I'd recommend making your CLI as short as possible and putting it at the bottom of the screen, OR putting it on a separate window entirely

If that doesn't fix your issue, I'll look through code & figure something out later today :)

**Comment by raspgalax** [comment]
I changed from Powershell to Cmd, and finally managed to get Exapunks to let me put a window over the top of it, and it works now. Quits after every 10 solves. Very cool and spooky to see it solving! Thanks for the help

**Comment by Will-Crain** [comment]
Glad you got it working. I've seen people fork this repo, but you're the first person to let me know you got it working. Brought a smile to my face 😄
